[package]
name = "aether_ai"
version = "1.0.0"
authors = ["AetherAI"]

[addresses]
aether_ai = "0x28b16dd6d82b32f9322547f77f465460f5354cc9587c09a0735001456efd3c3e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
